### ISSUE TITLE
Minor Code Cleanup

### ISSUE THREAD

**Issue by flancast90** [astronaut701/basic-ipleak-api-js#1]
Hey @astronaut701,

Really cool API example. I have a few minor nitpicks in case you want to cleanup the code a bit: 

- try/catch with the async/await is not necessary for the fetch() API. A more readable way to fetch() a URL would be with the .then().catch() syntax.

Here's an example of what I mean:
```js
fetch(url)
  .then(res => {
    // code here
  })
  .catch(err => {
    console.error(err);
  });
```

Looking forward to seeing how this project progresses!

**Comment by astronaut701** [comment]
Cleaned up the code! Thanks for that info, wasn't aware of that.
